# Generated by Django 5.1.7 on 2025-03-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collName', models.CharField(max_length=100)),
                ('collDesc', models.CharField(max_length=500)),
                ('collCover', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('pieceCover', models.CharField(max_length=1000)),
                ('Coll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.coll')),
            ],
        ),
    ]
